### ISSUE TITLE
Status badges do not show up properly

### ISSUE THREAD

**Issue by Alex-Yarkosky** [AVMf/avmf#21]
The two status badges that are in the `README.md` file currently do not show up as badges but linked text that lead to error 404 web pages from GitHub.

**Comment by enpuyou** [comment]
@Alex-Yarkosky Yes. Sorry for the error. I accidentally closed the issue. The badge is still missing due to the Travis and codecov.io have not been activated yet. I will work on this as soon as @gkapfham activates them. Thank you very much!

**Comment by gkapfham** [comment]
Hi @enpuyou can you find a time to soon meet with me so that we can work together to enable Travis CI integration? Thanks, I look forward to talking with you soon as I would also like to resolve this bug.

**Comment by enpuyou** [comment]
Yes @gkapfham, I wonder if we could work on this and solve it on Thursday during our regular meeting session. Also, I will try to activate this on my own fork today, so we can do this on master more smoothly.

**Comment by enpuyou** [comment]
This bug is fixed in the most recent commit 7d6c9ada5d67b6b972edb92716c3095c3d4ea29f
